apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - deployment.yaml
  - service.yaml

# TODO: add configMapGenerator/secretGenerator once values are finalized 