name: worldchef_mobile
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  widgetbook: ^3.14.0
  widgetbook_annotation: ^3.1.0
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1
dependency_overrides:
  accessibility_tools: ^2.6.0
flutter:
  uses-material-design: true 
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/src/assets/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: lib/src/assets/Nunito/Nunito-Bold.ttf
          weight: 700 