name: worldchef_mobile
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.0
  widgetbook: ^3.14.0
  widgetbook_annotation: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
dependency_overrides:
  accessibility_tools: ^2.6.0
flutter:
  uses-material-design: true 