version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    volumes:
      - ../backend:/usr/src/app/backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" 