apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldchef-api
  labels:
    app: worldchef-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worldchef-api
  template:
    metadata:
      labels:
        app: worldchef-api
    spec:
      containers:
        - name: api
          image: ghcr.io/worldchef/api:staging-<sha>
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "staging"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10 