apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - deployment.yaml
  - service.yaml

# Overlays / patches to be added for staging-specific env vars, secrets, and HPA 