name: Dev Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack & install dependencies
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Build TypeScript
        run: |
          yarn workspace worldchef-backend run build

      - name: Run unit tests
        run: |
          yarn test:ci
        env:
          SUPABASE_URL: https://myqhpmeprpaukgagktbn.supabase.co
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Deploy to Render via Deploy Hook
        env:
          RENDER_DEV_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEV_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEV_DEPLOY_HOOK_URL"

      - name: Notify Slack (placeholder)
        if: always()
        run: echo "TODO send Slack notification via workflo"