name: Dev Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & run tests
        run: |
          npm ci
          npm run test:ci

      - name: Debug Deploy Hook URL
        env:
          RENDER_DEV_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEV_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploy hook URL length: ${#RENDER_DEV_DEPLOY_HOOK_URL}"
          echo "Deploy hook URL starts with: ${RENDER_DEV_DEPLOY_HOOK_URL:0:30}..."
          if [ -z "$RENDER_DEV_DEPLOY_HOOK_URL" ]; then
            echo "ERROR: RENDER_DEV_DEPLOY_HOOK_URL secret is not set!"
            exit 1
          fi

      - name: Deploy to Render via Deploy Hook
        env:
          RENDER_DEV_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEV_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEV_DEPLOY_HOOK_URL"

      - name: Notify Slack (placeholder)
        if: always()
        run: echo "TODO send Slack notification via workflo"