name: Dev Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build & test
        run: |
          npm ci
          npm run test:ci

      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_DEV_SERVICE_ID }}
        run: |
          npx @render/cli deploy-service $RENDER_SERVICE_ID --branch develop --wait 600

      - name: Notify Slack (placeholder)
        run: echo "TODO: send Slack notification via workflow" 