name: Nightly Staging Data Refresh

on:
  schedule:
    # Runs at 03:00 UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    environment: staging-deploy
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node (for Supabase CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Outdated Node + npm-based Supabase CLI install removed; superseded by setup-cli action

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Debug file metadata
        run: |
          echo "=== File metadata before conversion ==="
          file staging/automation/nightly-refresh.sh || echo "File command failed"
          ls -la staging/automation/nightly-refresh.sh
          echo "=== First 5 lines (with control chars visible) ==="
          head -n 5 staging/automation/nightly-refresh.sh | cat -v

      - name: Run nightly-refresh script
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REFRESH_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -x
          echo "=== Environment check ==="
          echo "DATABASE_URL set: ${DATABASE_URL:+YES}"
          echo "SUPABASE_PROJECT_ID set: ${SUPABASE_PROJECT_ID:+YES}"
          
          echo "=== Installing dos2unix ==="
          sudo apt-get update && sudo apt-get install -y dos2unix
          
          echo "=== Converting line endings ==="
          dos2unix staging/automation/nightly-refresh.sh
          
          echo "=== File metadata after conversion ==="
          file staging/automation/nightly-refresh.sh
          ls -la staging/automation/nightly-refresh.sh
          
          echo "=== Setting permissions ==="
          chmod +x staging/automation/nightly-refresh.sh
          
          echo "=== Final file check ==="
          head -n 3 staging/automation/nightly-refresh.sh | cat -v
          
          echo "=== Executing script ==="
          bash staging/automation/nightly-refresh.sh 